### ISSUE TITLE
How to fix ModuleNotFoundError: No module named 'typings'

### ISSUE THREAD

**Issue by mrawesomey** [JasonLovesDoggo/RedditVideoMakerBot#67] opened 2022-06-08 20:37 UTC
![Image](https://user-images.githubusercontent.com/106691142/172712462-5fa0c30a-a3da-418f-aee5-164816e547c4.png)
DO I have to install something, I already tried installing a module called typings (I have the new version)

**Comment by StopmotionSimonYT** [comment] 2022-06-08 20:42
Have you tried: 
`pip3 install typings`

**Comment by JasonLovesDoggo** [comment] 2022-06-08 21:16
> Also sometimes the cookies option is in the VIdeo how do I get rid of it?

reclone

**Comment by JasonLovesDoggo** [comment] 2022-06-08 21:16
> ![Image](https://user-images.githubusercontent.com/106691142/172712462-5fa0c30a-a3da-418f-aee5-164816e547c4.png) DO I have to install something, I already tried installing a module called typings (I have the new version)

fixed in https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/2eac16f29d7daa3b83c0772a2dca19851d291fef

**Closed by JasonLovesDoggo** 2022-06-08 21:16 UTC

**Comment by mrawesomey** [comment] 2022-06-08 21:53
Ok thank you

**Comment by mrawesomey** [comment] 2022-06-08 21:57
But now it says this
![image](https://user-images.githubusercontent.com/106691142/172724444-aaac8fde-337a-4a62-af56-ac87d787146e.png)

**Comment by JasonLovesDoggo** [comment] 2022-06-08 21:59
> But now it says this ![image](https://user-images.githubusercontent.com/106691142/172724444-aaac8fde-337a-4a62-af56-ac87d787146e.png)

I changed the function's name.
did you reclone it?

**Comment by mrawesomey** [comment] 2022-06-08 22:11
Yup did everything and now happens everytime:
![image](https://user-images.githubusercontent.com/106691142/172726296-325c4993-c8fd-4c70-afc6-d518b13f30e8.png)

**Comment by JasonLovesDoggo** [comment] 2022-06-08 22:13
that is a different error that was caused by https://github.com/JasonLovesDoggo/RedditVideoMakerBot/pull/66
I just pushed a fix

**Comment by mrawesomey** [comment] 2022-06-08 22:22
And now this 
![image](https://user-images.githubusercontent.com/106691142/172727450-a22a7c81-a54b-4da5-8f60-63771585c2bf.png)

**Comment by JasonLovesDoggo** [comment] 2022-06-08 22:32
yep sorry again...
it's been fixed in my latest update.

I pushed before I tested on my last one.

> And now this ![image](https://user-images.githubusercontent.com/106691142/172727450-a22a7c81-a54b-4da5-8f60-63771585c2bf.png)
