### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by LeonNussbaum** [JasonLovesDoggo/RedditVideoMakerBot#94] opened 2022-06-12 18:42 UTC
Hello I got this error.
![grafik](https://user-images.githubusercontent.com/91377653/173248354-a7f8d4af-4c5d-4a0b-a107-98cea2fb143c.png)
```
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
This install of SoX cannot process .mp3 files.
Input formats were only specified for 0 out of 2 files.The last 2 files will remain unformatted.
This install of SoX cannot process .mp3 files.
Saving... ----------------------------------------   0% -:--:--
Traceback (most recent call last):
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\main.py", line 62, in <module>
    main()
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\main.py", line 40, in main
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\video_creation\voices.py", line 51, in save_text_to_mp3
    ttttsw.tts(
  File "C:\Users\Leon\Desktop\RedditVideoMakerBot-master\video_creation\TTSwrapper.py", line 125, in tts
    cbn.build(audio_clips, filename, "concatenate")
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\combine.py", line 87, in build
    _validate_file_formats(input_filepath_list, combine_type)
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\combine.py", line 319, in _validate_file_formats
    _validate_sample_rates(input_filepath_list, combine_type)
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\combine.py", line 328, in _validate_sample_rates
    sample_rates = [
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\combine.py", line 329, in <listcomp>
    file_info.sample_rate(f) for f in input_filepath_list
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\file_info.py", line 205, in sample_rate
    output = soxi(input_filepath, 'r')
  File "C:\Users\Leon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sox\core.py", line 147, in soxi
    shell_output = subprocess.check_output(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by StopmotionSimonYT** [comment] 2022-06-12 18:44
This error is a duplicate of #88. There is no fix yet.

**Closed** 2022-06-12 18:51 UTC

**Comment by brokencommit** [comment] 2022-06-12 20:48
i fixed mine by nuking python3 and reinstalling.

**Comment by ArshadhAX** [comment] 2022-06-17 12:47
I reinstalled Python, didn't work
