### ISSUE TITLE
Is it possible to read text below title? 

### ISSUE THREAD

**Issue by edvinas1** [JasonLovesDoggo/RedditVideoMakerBot#93] opened 2022-06-12 12:24 UTC
Hi, as i noticed it just reads tittle but not text below title is it possible to change it and if yes where ?

**Comment by StopmotionSimonYT** [comment] 2022-06-12 12:30
In video_creation/voices.py:38 STORYMODE is requested from the .env. I don't know what this does but you can give it a try by adding STORYMODE=true in the .env file.

**Comment by StopmotionSimonYT** [comment] 2022-06-12 12:31
We are working on a story mode.

**Comment by JasonLovesDoggo** [comment] 2022-06-12 14:50
Please give me time as my finger is literally cut in half right now and I can't use my left arm

If somebody continues my work on that feature I will be happy to merge it but I cannot code at the moment

**Comment by JasonLovesDoggo** [comment] 2022-06-12 14:51
Duplicate of #10

**Closed** 2022-06-12 14:51 UTC
